### ISSUE TITLE
Sentinl v6.8.4 not working in Kibana 7.6 please help

### ISSUE THREAD

**Issue by rohitsawant02** [sentinl/sentinl#791]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |  7.6       |
| Elasticsearc |    7.6     |
| Server OS    |   windows 10      |
| Browser      |     chrome    |

#### Original Install Method

- [ ] Release pkg link
- [ ] Gulp
- [ ] Source
- Other: 

#### Steps to Reproduce
1. put sentinl plugin into kibana/plugins folder 
2. run command yarn start
3.

#### Sample of data you have in Elasticsearch
```
```

#### Full Watcher JSON
```
```

#### Errors in Browser Console (if relevant)
```][Sentinl][init] setting puppeteer report engine: Error: puppeter chrome was not found
server    log   [09:18:18.838] [info][Sentinl][init_indices] checking watcher_alarms-2021.02.11 index ...
server    log   [09:18:18.838] [error][Sentinl][init] start: Error: init indices: Error: create index: TypeError: Cannot read property 'exists' of undefined

Unhandled Promise rejection detected:

Error: Get hosts from config: ReferenceError: server is not defined
    at gethosts (E:\kibana-dev\branch\kibana\plugins\sentinl\/init.js:92:11)
    at E:\kibana-dev\branch\kibana\plugins\sentinl\/init.js:193:20
    at init (E:\kibana-dev\branch\kibana\node_modules\lodash\lodash.js:10076:25)
    at Plugin.externalInit (E:\kibana-dev\branch\kibana\plugins\sentinl\/init.js:238:5)
    at Object.register (E:\kibana-dev\branch\kibana\src\legacy\server\plugins\lib\/plugin.js:88:20)
    at internals.Server.register (E:\kibana-dev\branch\kibana\node_modules\hapi\lib\server.js:431:35)
    at Plugin.init (E:\kibana-dev\branch\kibana\src\legacy\server\plugins\lib\/plugin.js:92:28)
    at Plugin.init (E:\kibana-dev\branch\kibana\node_modules\lodash\lodash.js:10076:25)
    at callPluginHook (E:\kibana-dev\branch\kibana\src\legacy\server\plugins\lib\/call_plugin_hook.js:49:9)
```

**Comment by lmangani** [comment]
@rohitsawant02 thanks for trying and your report, but unfortunately this is the expected outcome - the version of the plugin and kibana must be the same. new builds will be created for apache2 kibana going forward, at this time no ETA yet. Please see the readme, feel free to donate towards new versions being supported

**Comment by rohitsawant02** [comment]
@Imangani thanks for quick reply. I got below error while I have done some changes like:
1) put configuration xpack.reporting.capture.browser.type: phantom in Kibana.yml 

Error:
 [error][Sentinl][init] setting puppeteer report engine: Error: puppeter chrome was not found
server    log   [10:06:49.823] [fatal][root] Error: Unknown config key: elasticsearch.hosts
    at Config.get (E:\kibana-dev\branch\kibana\src\legacy\server\config\/config.js:148:15)
    at E:\kibana-dev\branch\kibana\plugins\sentinl\/init.js:156:19
    at init (E:\kibana-dev\branch\kibana\node_modules\lodash\lodash.js:10076:25)
    at Plugin.externalInit (E:\kibana-dev\branch\kibana\plugins\sentinl\/init.js:217:5)
    at Object.register (E:\kibana-dev\branch\kibana\src\legacy\server\plugins\lib\/plugin.js:88:20)
    at internals.Server.register (E:\kibana-dev\branch\kibana\node_modules\hapi\lib\server.js:431:35)
    at Plugin.init (E:\kibana-dev\branch\kibana\src\legacy\server\plugins\lib\/plugin.js:92:28)
    at Plugin.init (E:\kibana-dev\branch\kibana\node_modules\lodash\lodash.js:10076:25)
    at callPluginHook (E:\kibana-dev\branch\kibana\src\legacy\server\plugins\lib\/call_plugin_hook.js:49:9)
server    log   [10:06:49.901] [info][plugins-system] Stopping all plugins.

**Comment by rohitsawant02** [comment]
> @rohitsawant02 thanks for trying and your report, but unfortunately this is the expected outcome - the version of the plugin and kibana must be the same. new builds will be created for apache2 kibana going forward, at this time no ETA yet. Please see the readme, feel free to donate towards new versions being supported

@Imangani thanks for quick reply. I got below error while I have done some changes like:

put configuration xpack.reporting.capture.browser.type: phantom in Kibana.yml
Error:
[error][Sentinl][init] setting puppeteer report engine: Error: puppeter chrome was not found
server log [10:06:49.823] [fatal][root] Error: Unknown config key: elasticsearch.hosts
at Config.get (E:\kibana-dev\branch\kibana\src\legacy\server\config/config.js:148:15)
at E:\kibana-dev\branch\kibana\plugins\sentinl/init.js:156:19
at init (E:\kibana-dev\branch\kibana\node_modules\lodash\lodash.js:10076:25)
at Plugin.externalInit (E:\kibana-dev\branch\kibana\plugins\sentinl/init.js:217:5)
at Object.register (E:\kibana-dev\branch\kibana\src\legacy\server\plugins\lib/plugin.js:88:20)
at internals.Server.register (E:\kibana-dev\branch\kibana\node_modules\hapi\lib\server.js:431:35)
at Plugin.init (E:\kibana-dev\branch\kibana\src\legacy\server\plugins\lib/plugin.js:92:28)
at Plugin.init (E:\kibana-dev\branch\kibana\node_modules\lodash\lodash.js:10076:25)
at callPluginHook (E:\kibana-dev\branch\kibana\src\legacy\server\plugins\lib/call_plugin_hook.js:49:9)
server log [10:06:49.901] [info][plugins-system] Stopping all plugins.

**Comment by lmangani** [comment]
6.8 to 7.6 is a huge jump and the anti-competitive fellas at Elastic did everything they could to make it incompatible. This most likely requires hundreds of changes.

**Comment by rohitsawant02** [comment]
> 6.8 to 7.6 is a huge jump and the anti-competitive fellas at Elastic did everything they could to make it incompatible. This most likely requires hundreds of changes.

@lmangani I have found 7.6 release which seems unstable but I am trying to install and will try to solve issue. let know the guidance referece link if any

**Comment by rohitsawant02** [comment]
> 6.8 to 7.6 is a huge jump and the anti-competitive fellas at Elastic did everything they could to make it incompatible. This most likely requires hundreds of changes.

hi @lmangani ,

I need to upgrade sentinl to work with kibana 7.9 and 7.10. please share latest code repository and kindly guide me how to upgrade sentinl plugin for Kibana 7.9 and above, I will keep on upgrading repository with development advice by you. so that it remains open source .please include me in your devlopment team.you might be in need of sentinl plugin developer for Kibana latest version. I am more interested in report(screenshot) generation and schedule an automatic mailing to a registered recipient.

**Comment by lmangani** [comment]
Thank you for taking initiative @rohitsawant02 its much appreciated and we need all the help we can get - unfortunately this tedious task requires time and expertise on both the plugin and kibana codebases - do you have any previous experience in this context? 

In either case, I would suggest opening a dedicated issue for this mission first and foremost instead of this closed issue, where You can request help of others from the new group.
